const MESSAGE = {
  CHANGE_STATUS_SECTION_SUCCESS_FULL: 'Thay đổi trạng thái cấu phần thành công',
  CHANGE_STATUS_SECTION_FAILED: 'Thay đổi trạng thái cấu phần không thành công',
  SECTION_IS_REQUIRED: 'Bạn phải nhập vào tên của cấu phần',
  ADD_SECTION_SUCCESS_FULL: 'Thêm cấu phần thành công',
  ADD_SECTION_FAILED: 'Thêm cấu phần không thành công',
  CHANGE_SECTION_SUCCESS_FULL: 'Sửa cấu phần thành công',
  CHANGE_SECTION_FAILED: 'Sửa cấu phần không thành công',
  _CODE: 'Lấy đơn đặt hàng sản phẩm không thành công',
  GET_UNIT_STATUS: 'Không lấy được trạng thái các đơn hàng!',
  CHANGE_STATUS_PRODUCT_SUCCESS_FULL: 'Thay đổi trạng thái sản phẩm thành công',
  CHANGE_STATUS_PRODUCT_FAILED: 'Thay đổi trạng thái sản phẩm không thành công',
  PRODUCT_IS_REQUIRED: 'Bạn phải nhập vào tên của sản phẩm',
  ADD_PRODUCT_SUCCESS_FULL: 'Thêm sản phẩm thành công',
  ADD_PRODUCT_EXISTS: 'Tên sản phẩm đã tồn tại !',
  LIST_PROVIDER: 'Không thể lấy được danh sách nhà cung cấp',
  ADD_USER_PROVIDERS: 'Không tạo được người dùng',
  DETAIL_PROVIDER: 'Không sửa được thông tin người dùng',
  DELETE: 'Không thể xóa người dùng',
  LIST_AGENCY: 'Không thể lấy được danh sách đại lý',
  ADD_USER_AGENCY: 'Không tạo được người dùng',
  UPDATE_USER_FAILED: 'Không sửa được thông tin người dùng',
  UPDATE_USER_SUCCESS_FULL: 'Cập nhật thông tin người dùng thành công',
  PASSWORD: 'Người dùng sẽ phải đổi mật khẩu trong lần đăng nhập sau.',
  REPAIR_STATUS: {
    SUCCESS: 'Cập nhật sản phẩm thành công',
    ERROR: 'Không thể cấu phần sản phẩm',
  },
  LOCK: 'Không thể khóa sản phẩm',
  UN_LOCK: 'Không thể mở khóa sản phẩm',
  SAVE_ERROR: 'Cập nhật sản phẩm không thành công',
  SAVE: 'Cập nhật sản phẩm thành công',
  REVIEW_ERROR: 'Hãy điền đánh giá của bạn',
  UPDATE_SUCCESSFUL: 'Cập nhật thành công',
  UPDATE_FAILED: 'Cập nhật thất bại',
  GET_PRODUCT_DATA_FAILED: 'Không thể lấy dữ liệu sản phẩm',
  SEND_EMAIL_SUCCESS: 'Gửi email thành công',
  SEND_EMAIL_FALSE: 'Gửi email không thành công',
  REFUND_ALLOCATION:
    'Không được phép nhập số tiền hoàn trả quá số tiền đã đóng',
  PAY_ALLOCATION_ERROR:
    'Không được phép nhập số tiền đóng thêm lớn hơn số tiền phân bổ khả dụng',
  INPUT_BIGGER: 'Số tiền nhập phải lớn hơn 0',
  CHANGE_STATUS_SUCCESS_FULL: 'Thay đổi trạng thái mã giảm giá thành công',
  UNABLE_TO_OPERATE: 'Không thể thao tác tác vụ',
  ADD_CODE_SUCCESS: 'Thêm mã giảm giá thành công',
  ADD_CODE: 'Mã giảm giá đã tồn tại',
  PRODUCT_ERROR: 'Không có dữ liệu sản phẩm',
  TYPE_ERROR: 'Không có loại mã giảm giá',
  NAME_COINCIDE_AGENCY: 'Tên đại lý đã tồn tại!',
  ADD_AGENCY_STATUS: {
    ERROR: 'Không thể thêm đại lý',
    SUCCESS: 'Thêm đại lý thành công',
  },
  LIST_ERROR: 'Không lấy được danh sách gói đã mua',
  LIST_PRODUCT_ERROR: 'Không lấy được danh sách sản phẩm',
  LIST_PACKAGE_ERROR: 'Không lấy được danh sách gói sản phẩm',
  ORDER_DETAIL_ERROR: 'Không lấy được thông tin sản phẩm',
  ADD_ERROR: 'Mua gói sản phẩm không thành công',
  ADD_SUCCESS: 'Mua mới sản phẩm thành công',
  DELETE_ERROR: 'Không hủy được sản phẩm',
  LIST_BANK_ERROR: 'Lấy danh sách ngân hàng không thành công',
  USER_DETAIL_ERROR: 'Lấy thông tin chủ tài khoản không thành công',
  DISCOUNT_CODE_ERROR: 'Không có mã giảm giá',
  ADDITIONALY_ERROR:
    'Không được phép nhập số tiền đóng thêm lớn hơn số tiền phải thu',
  RETURN_ERROR: 'Không được phép nhập số tiền hoàn trả lớn hơn số tiền đã đóng',
  CHANGE_ACTION_SUCCESS_FULL:
    'Bạn đã thay đổi trạng thái gói sản phẩm thành công',
  CHANGE_ACTION_FAILED: 'Thay đổi trạng thái gói sản phẩm không thành công',
  PACKAGE_PRODUCT_IS_REQUIRED: 'Bạn phải nhập vào tên gói sản phẩm',
  ADD_PACKAGE_PRODUCT_SUCCESS_FULL: 'Thêm gói sản phẩm thành công',
  ADD_PACKAGE_PRODUCT_DUPLICATE: 'Tên gói sản phẩm đã tồn tại',
  ADD_PACKAGE_PRODUCT_FAILED: 'Thêm gói sản phẩm không thành công',
  CHANGE_PACKAGE_PRODUCT_SUCCESS_FULL: 'Sửa gói sản phẩm thành công',
  CHANGE_PACKAGE_PRODUCT_FAILED: 'Sửa gói sản phẩm không thành công',
  INVALID_PRODUCTS: 'Gói sản phẩm phải có ít nhất một sản phẩm !',
  GET_DETAIL_AGENCY_FAILED: 'Không tìm thấy chi tiết đại lý',
  INVALID_PROMOTION_CODE: 'Mã giảm giá phải có 7 kí tự và là in hoa',
  COST: 'Không được để trống',
  CHANGE_ACTION_DISCOUNT_SUCCESS_FULL:
    'Bạn đã thay đổi trạng thái mã giảm giá thành công',
  CHANGE_ACTION_DISCOUNT_FAILED:
    'Thay đổi trạng thái mã giảm giá không thành công',
  INVALID_MAX_DISCOUNT: 'Giá giảm tối đa không hợp lệ',
  ADD_NEW_PROMOTION_CODE_SUCCESS_FULL: 'Thêm mã giảm giá thành công',
  ADD_NEW_PROMOTION_CODE_FAILED: 'Thêm mã giảm giá không thành công',
  GET_INFORMATION_FAILED: 'Lấy thông tin bảng điều khiển không thành công!',
  DATA_ERROR: 'Không có dữ liệu mã giảm giá',
  FETCH_DATA_FAILED: 'Lấy dữ liệu thất bại',
  GET_DETAIL_CUSTOMER_FAILED: 'Lấy thông tin người dùng thất bại',
  PAY_ERROR:
    'Số tiền Đã phân bổ đang lớn hơn Số tiền đã đóng. Vui lòng phân bổ lại tại màn hình chi tiết đơn hàng',
  INVALID_PHONE_NUMBER: 'Số điện thoại không đúng',
  PHONE_NUMBER_IS_REQUIRED: 'Số điện thoại là trường bắt buộc',
  INVALID_EMAIL: 'Email không đúng định dạng',
  EMAIL_IS_REQUIRED: 'Email là trường bắt buộc',
  UPDATE_INFORMATION_SUCCESS_FULL: 'Cập nhật thông tin thành công',
  UPDATE_INFORMATION_FAILED: 'Cập nhật thông tin không thành công',
};
export default MESSAGE;
